<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5b0a413a-1fe4-4857-a7f8-d2db67c5a447</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.73.0.4029" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="BlazorApp1\appsettings.Development.json" />
    <_ContentIncludedByDefault Remove="BlazorApp1\appsettings.json" />
    <_ContentIncludedByDefault Remove="BlazorApp1\obj\BlazorApp1.csproj.nuget.dgspec.json" />
    <_ContentIncludedByDefault Remove="BlazorApp1\obj\project.assets.json" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Properties\launchSettings.json" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\AccessDenied.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\ConfirmEmail.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\ConfirmEmailChange.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\ExternalLogin.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\ForgotPassword.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\ForgotPasswordConfirmation.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\InvalidPasswordReset.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\InvalidUser.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Lockout.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Login.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\LoginWith2fa.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\LoginWithRecoveryCode.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\ChangePassword.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\DeletePersonalData.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\Disable2fa.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\Email.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\EnableAuthenticator.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\ExternalLogins.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\GenerateRecoveryCodes.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\Index.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\PersonalData.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\ResetAuthenticator.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\SetPassword.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\TwoFactorAuthentication.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\_Imports.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Register.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\RegisterConfirmation.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\ResendEmailConfirmation.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\ResetPassword.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\ResetPasswordConfirmation.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\_Imports.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Shared\ExternalLoginPicker.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Shared\ManageLayout.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Shared\ManageNavMenu.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Shared\RedirectToLogin.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Shared\ShowRecoveryCodes.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Shared\StatusMessage.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\App.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Layout\MainLayout.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Layout\NavMenu.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Pages\Auth.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Pages\Counter.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Pages\Error.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Pages\Home.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Pages\Weather.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Routes.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\_Imports.razor" />
    <_ContentIncludedByDefault Remove="WebApplication1\appsettings.Development.json" />
    <_ContentIncludedByDefault Remove="WebApplication1\appsettings.json" />
    <_ContentIncludedByDefault Remove="WebApplication1\obj\project.assets.json" />
    <_ContentIncludedByDefault Remove="WebApplication1\obj\WebApplication1.csproj.nuget.dgspec.json" />
    <_ContentIncludedByDefault Remove="WebApplication1\Properties\launchSettings.json" />
    <_ContentIncludedByDefault Remove="WebApplication1\Areas\Identity\Pages\_ViewStart.cshtml" />
    <_ContentIncludedByDefault Remove="WebApplication1\Views\Home\Index.cshtml" />
    <_ContentIncludedByDefault Remove="WebApplication1\Views\Home\Privacy.cshtml" />
    <_ContentIncludedByDefault Remove="WebApplication1\Views\Shared\Error.cshtml" />
    <_ContentIncludedByDefault Remove="WebApplication1\Views\Shared\_Layout.cshtml" />
    <_ContentIncludedByDefault Remove="WebApplication1\Views\Shared\_LoginPartial.cshtml" />
    <_ContentIncludedByDefault Remove="WebApplication1\Views\Shared\_ValidationScriptsPartial.cshtml" />
    <_ContentIncludedByDefault Remove="WebApplication1\Views\_ViewImports.cshtml" />
    <_ContentIncludedByDefault Remove="WebApplication1\Views\_ViewStart.cshtml" />
    <_ContentIncludedByDefault Remove="WebApp1\appsettings.Development.json" />
    <_ContentIncludedByDefault Remove="WebApp1\appsettings.json" />
    <_ContentIncludedByDefault Remove="WebApp1\obj\project.assets.json" />
    <_ContentIncludedByDefault Remove="WebApp1\obj\WebApp1.csproj.nuget.dgspec.json" />
    <_ContentIncludedByDefault Remove="WebApp1\Properties\launchSettings.json" />
    <_ContentIncludedByDefault Remove="WebApp1\Areas\Identity\Pages\_ViewStart.cshtml" />
    <_ContentIncludedByDefault Remove="WebApp1\Pages\Error.cshtml" />
    <_ContentIncludedByDefault Remove="WebApp1\Pages\Index.cshtml" />
    <_ContentIncludedByDefault Remove="WebApp1\Pages\Privacy.cshtml" />
    <_ContentIncludedByDefault Remove="WebApp1\Pages\Shared\_Layout.cshtml" />
    <_ContentIncludedByDefault Remove="WebApp1\Pages\Shared\_LoginPartial.cshtml" />
    <_ContentIncludedByDefault Remove="WebApp1\Pages\Shared\_ValidationScriptsPartial.cshtml" />
    <_ContentIncludedByDefault Remove="WebApp1\Pages\_ViewImports.cshtml" />
    <_ContentIncludedByDefault Remove="WebApp1\Pages\_ViewStart.cshtml" />
    <_ContentIncludedByDefault Remove="wwwroot\banners\214a51bf-26c7-4000-981d-a06e543cb1a1.png" />
    <_ContentIncludedByDefault Remove="wwwroot\2cc9e673-34fc-4c83-8df1-fc16c72ba882\avatar_20251124_001439.png" />
    <_ContentIncludedByDefault Remove="wwwroot\2cc9e673-34fc-4c83-8df1-fc16c72ba882\background_20251124_002108.png" />
    <_ContentIncludedByDefault Remove="wwwroot\2cc9e673-34fc-4c83-8df1-fc16c72ba882\banner_20251124_001904.png" />
    <_ContentIncludedByDefault Remove="wwwroot\08595e01-bb81-4f88-bf09-853fce02c8ae\avatar_20251128_183201.png" />
    <_ContentIncludedByDefault Remove="wwwroot\Archive\3236724b-b663-4fb1-a554-21eb725656c0\swf_639000509879694471.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\Archive\3236724b-b663-4fb1-a554-21eb725656c0\thumbnail_639000509879613898.png" />
    <_ContentIncludedByDefault Remove="wwwroot\Archive\692fdcc1-e8e4-47d1-937b-0b100b69d966\swf_639000619109970708.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\Archive\692fdcc1-e8e4-47d1-937b-0b100b69d966\thumbnail_639000619109883532.png" />
    <_ContentIncludedByDefault Remove="wwwroot\Profile\f9da8037-e1a8-4681-9d30-7117e4e88e57\avatar_20251201_004944.png" />
    <_ContentIncludedByDefault Remove="wwwroot\Archive\5f2d4f39-d876-4e65-802a-8f95808e2104\swf_639004937734459639.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\Archive\5f2d4f39-d876-4e65-802a-8f95808e2104\thumbnail_639004937734398092.png" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\users\1c524396ae7d418ab599e8d76dd1fcd0\avatar\94f17d9b5763477b944fdd19e5d4dde1.png" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\users\39f0db990fc34d73a2c6bcda641bc42a\avatar\71b47c9e61904eb6a13a063aec84b23b.png" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\users\6c0a3b894b5843bab9af5ba27e6286bb\avatar\bc81a28f9ba440558dd7fbfc4d898eb4.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Email\" />
    <Folder Include="Repositories\Archive\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
