<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5b0a413a-1fe4-4857-a7f8-d2db67c5a447</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.73.0" />
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.73.0.4029" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="BlazorApp1\appsettings.Development.json" />
    <_ContentIncludedByDefault Remove="BlazorApp1\appsettings.json" />
    <_ContentIncludedByDefault Remove="BlazorApp1\obj\BlazorApp1.csproj.nuget.dgspec.json" />
    <_ContentIncludedByDefault Remove="BlazorApp1\obj\project.assets.json" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Properties\launchSettings.json" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\AccessDenied.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\ConfirmEmail.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\ConfirmEmailChange.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\ExternalLogin.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\ForgotPassword.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\ForgotPasswordConfirmation.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\InvalidPasswordReset.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\InvalidUser.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Lockout.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Login.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\LoginWith2fa.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\LoginWithRecoveryCode.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\ChangePassword.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\DeletePersonalData.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\Disable2fa.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\Email.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\EnableAuthenticator.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\ExternalLogins.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\GenerateRecoveryCodes.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\Index.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\PersonalData.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\ResetAuthenticator.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\SetPassword.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\TwoFactorAuthentication.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Manage\_Imports.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\Register.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\RegisterConfirmation.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\ResendEmailConfirmation.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\ResetPassword.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\ResetPasswordConfirmation.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Pages\_Imports.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Shared\ExternalLoginPicker.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Shared\ManageLayout.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Shared\ManageNavMenu.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Shared\RedirectToLogin.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Shared\ShowRecoveryCodes.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Account\Shared\StatusMessage.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\App.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Layout\MainLayout.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Layout\NavMenu.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Pages\Auth.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Pages\Counter.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Pages\Error.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Pages\Home.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Pages\Weather.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\Routes.razor" />
    <_ContentIncludedByDefault Remove="BlazorApp1\Components\_Imports.razor" />
    <_ContentIncludedByDefault Remove="WebApplication1\appsettings.Development.json" />
    <_ContentIncludedByDefault Remove="WebApplication1\appsettings.json" />
    <_ContentIncludedByDefault Remove="WebApplication1\obj\project.assets.json" />
    <_ContentIncludedByDefault Remove="WebApplication1\obj\WebApplication1.csproj.nuget.dgspec.json" />
    <_ContentIncludedByDefault Remove="WebApplication1\Properties\launchSettings.json" />
    <_ContentIncludedByDefault Remove="WebApplication1\Areas\Identity\Pages\_ViewStart.cshtml" />
    <_ContentIncludedByDefault Remove="WebApplication1\Views\Home\Index.cshtml" />
    <_ContentIncludedByDefault Remove="WebApplication1\Views\Home\Privacy.cshtml" />
    <_ContentIncludedByDefault Remove="WebApplication1\Views\Shared\Error.cshtml" />
    <_ContentIncludedByDefault Remove="WebApplication1\Views\Shared\_Layout.cshtml" />
    <_ContentIncludedByDefault Remove="WebApplication1\Views\Shared\_LoginPartial.cshtml" />
    <_ContentIncludedByDefault Remove="WebApplication1\Views\Shared\_ValidationScriptsPartial.cshtml" />
    <_ContentIncludedByDefault Remove="WebApplication1\Views\_ViewImports.cshtml" />
    <_ContentIncludedByDefault Remove="WebApplication1\Views\_ViewStart.cshtml" />
    <_ContentIncludedByDefault Remove="WebApp1\appsettings.Development.json" />
    <_ContentIncludedByDefault Remove="WebApp1\appsettings.json" />
    <_ContentIncludedByDefault Remove="WebApp1\obj\project.assets.json" />
    <_ContentIncludedByDefault Remove="WebApp1\obj\WebApp1.csproj.nuget.dgspec.json" />
    <_ContentIncludedByDefault Remove="WebApp1\Properties\launchSettings.json" />
    <_ContentIncludedByDefault Remove="WebApp1\Areas\Identity\Pages\_ViewStart.cshtml" />
    <_ContentIncludedByDefault Remove="WebApp1\Pages\Error.cshtml" />
    <_ContentIncludedByDefault Remove="WebApp1\Pages\Index.cshtml" />
    <_ContentIncludedByDefault Remove="WebApp1\Pages\Privacy.cshtml" />
    <_ContentIncludedByDefault Remove="WebApp1\Pages\Shared\_Layout.cshtml" />
    <_ContentIncludedByDefault Remove="WebApp1\Pages\Shared\_LoginPartial.cshtml" />
    <_ContentIncludedByDefault Remove="WebApp1\Pages\Shared\_ValidationScriptsPartial.cshtml" />
    <_ContentIncludedByDefault Remove="WebApp1\Pages\_ViewImports.cshtml" />
    <_ContentIncludedByDefault Remove="WebApp1\Pages\_ViewStart.cshtml" />
    <_ContentIncludedByDefault Remove="wwwroot\banners\214a51bf-26c7-4000-981d-a06e543cb1a1.png" />
    <_ContentIncludedByDefault Remove="wwwroot\2cc9e673-34fc-4c83-8df1-fc16c72ba882\avatar_20251124_001439.png" />
    <_ContentIncludedByDefault Remove="wwwroot\2cc9e673-34fc-4c83-8df1-fc16c72ba882\background_20251124_002108.png" />
    <_ContentIncludedByDefault Remove="wwwroot\2cc9e673-34fc-4c83-8df1-fc16c72ba882\banner_20251124_001904.png" />
    <_ContentIncludedByDefault Remove="wwwroot\08595e01-bb81-4f88-bf09-853fce02c8ae\avatar_20251128_183201.png" />
    <_ContentIncludedByDefault Remove="wwwroot\Archive\3236724b-b663-4fb1-a554-21eb725656c0\swf_639000509879694471.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\Archive\3236724b-b663-4fb1-a554-21eb725656c0\thumbnail_639000509879613898.png" />
    <_ContentIncludedByDefault Remove="wwwroot\Archive\692fdcc1-e8e4-47d1-937b-0b100b69d966\swf_639000619109970708.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\Archive\692fdcc1-e8e4-47d1-937b-0b100b69d966\thumbnail_639000619109883532.png" />
    <_ContentIncludedByDefault Remove="wwwroot\Profile\f9da8037-e1a8-4681-9d30-7117e4e88e57\avatar_20251201_004944.png" />
    <_ContentIncludedByDefault Remove="wwwroot\Archive\5f2d4f39-d876-4e65-802a-8f95808e2104\swf_639004937734459639.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\Archive\5f2d4f39-d876-4e65-802a-8f95808e2104\thumbnail_639004937734398092.png" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\users\1c524396ae7d418ab599e8d76dd1fcd0\avatar\94f17d9b5763477b944fdd19e5d4dde1.png" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\users\39f0db990fc34d73a2c6bcda641bc42a\avatar\71b47c9e61904eb6a13a063aec84b23b.png" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\users\6c0a3b894b5843bab9af5ba27e6286bb\avatar\bc81a28f9ba440558dd7fbfc4d898eb4.png" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\217e5ca7e62e4b97a24ab6ad1e94b484\flash\1d27624ac4be45a0b0f93df1350ee697.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\217e5ca7e62e4b97a24ab6ad1e94b484\flash\b87503ad0dc54e4eba59f7edaae3144f.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\217e5ca7e62e4b97a24ab6ad1e94b484\flash\e7c31982452d49e194a23090aafa5b42.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\217e5ca7e62e4b97a24ab6ad1e94b484\thumbnail\0dfb988438814f98817a7cb6a702b54a.png" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\217e5ca7e62e4b97a24ab6ad1e94b484\thumbnail\3af95292218045d991293657672588b4.png" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\217e5ca7e62e4b97a24ab6ad1e94b484\thumbnail\d59091bf98e741a08e6a35a07cf80725.png" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\0f36c2b447d145189657a89269c15c28\flash\7d13674af13d4879aab096a0f723a6f1.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\115604c2b2d548e1a02ed57001422d39\flash\563f0f9f452541769605772e48b1332c.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\21bd2c58d7e540e2a29e83df24bdf565\flash\069055afc11c4fd5a2777d206628296c.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\2c3284c8471a4977ba8d6c24594468e7\flash\8c28b97be6aa404e9feba899c97e5b12.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\33fe3e6e7d274c0b8bcd2bf3dd8b624a\flash\388041d106214ffdb059375dcede49bb.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\35264ea6627745ba8cd7756ec2544d59\flash\6cf91954898c49fe9b3aa9b4a8c452ef.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\36afb9ce17554802b1709dacac1d5f18\flash\e2c7085dc4bb4fa39ea674c9ef5ba583.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\378b5a157c824eca8e694b68ef261014\flash\622c98f0f9e54620804eee088b5df70e.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\3916f2786a664a3e8318cd82219e4391\flash\964f94ee0a174ef080f09b642251cbc1.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\3b72bbaf53de4cc18b7bcd320aad6272\flash\8c2fb122f46d4e3a9225527648fb2ae0.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\3c99b3da32ee460fabf30aec68a9cf66\flash\91fb793e914f4e9ebb58d1b6c413d212.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\3e4931a730134fd79422519988395b74\flash\b0435f1bfe8f4a3f9d2ae98ef19a51dc.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\4f62830dcfaa4c638baf4534011e2b1a\flash\4b73dfd120b446ff880ed7309f5aa622.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\518ec8b5cedc453c8701cc7d3971c975\flash\57f6eede54e84279916e0cd706bba275.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\53ab268aa7f34db69cadc489527b1916\flash\0ad75fbbc40d40a6bfc15ccb7f7c18b9.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\543d7dc0f5464f60bc5e2a9dfc9ffff6\flash\cdc37f9150fc47e8aa3174c715d8f8c8.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\55fc321448ce42b785377d28c2619048\flash\3de4683fc519489fac5e67c8c94928b2.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\5808f401e12f4ba5bb0bbf34e1e7d02b\flash\4fb0445b8de74116a879e5f3355d0a6e.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\6a21eb21a06640239f42d88813d0c4e5\flash\5e8092fa1418431a8182ea6bd175164d.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\7fa80593ada74d4abb688163c54f63d5\flash\1114a371d207437caebeb44d4b092046.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\86c3c69dfe7443ed80737860a79ac218\flash\cd0a00fd22064405948fbda8fb8d8764.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\879f72a6c11a44d7aae8376dc966f875\flash\c058a80d065b470d9bf39117c320f606.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\958797700d394d198d9f720759da4ecc\flash\aa8992da9adc48c993d4027e664223e1.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\9c56e636df84449f81afd37822e82744\flash\b7fb1aa4735c469390c4cc6a5da9d185.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\a2b9b9979edb4dbabf4c9cd779048f68\flash\84235b550b174ba2aa820cd0a966ac1f.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\a5353b8238b04edfb3c4c198c68bc064\flash\d7de8d2d5033459d8ee3a20e546bc281.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\a638f4a746aa40b6a46d4f13dad889c6\flash\ba730609ac8440fd9a6588a711f1bab4.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\aabc486b889b43cdad8b0e27fddfe6e9\flash\b968293ba7bf4c85b8d74df888a364a6.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\b13bc33a957a4c5d9cfd807d40498d61\flash\d5a3d319cc5a4c7199f3d7cf9f1c7bff.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\b909ee8c44164cd68af60e5342a376f2\flash\1d8a9b33888540919cd91d31564916b4.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\b909ee8c44164cd68af60e5342a376f2\thumbnail\1d3aa65159cb4e16bdb725df8be04a34.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\cbf3dbfd457f4f6dbc37ada678537e23\flash\fa1b2077c16b473f8caa49956d3e388b.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\d29705d7b2054e9d9a62dac0beedd909\flash\07dc5b8451f94b238d1307ae15a69c10.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\d2bda1b9fb294e35a23362c0900ceacd\flash\ae210b092f3d47d69e205a20df80caff.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\d4f327043c924678afb59ab948164c5f\flash\bb7846d3d03f4ff2a2331eac3ff94a92.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\d6675289907e4f90824abeaaef1e7d23\flash\ee3f4444f43d45d9836ad5ea31364534.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\d6cb37f9ca5f4816b1f9bc0c8cb0125d\flash\20d67e120e6d4818b22e664c9b023030.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\dd316fadde7546d295a599ccf7b2ae4c\flash\3466c5e980334da4876b20b5471d927f.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\def564cd5ae54326b536b4bdea239da0\flash\60e8d8826cd8464780e11baa967c5907.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\e12b9a26b95948c884c1eec81134f188\flash\ab0b2b46a0a74c0993ec48c15949d629.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\e2eb0386dc6940b28e9d9ed5688807bc\flash\71536d665ffc4cb58241df05e18aca58.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\f49516532700467892fd8af55af6f155\flash\0a88a1d47426401aafa49cb3145fb364.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\f5559070e97b482198f0f1dd5703b51f\flash\f861c283b44743cabf3689ab2b04ddb9.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\f8717a38beaa490ea1379c790efdef01\flash\e91eb65d21204015ac55ce3308ee6d62.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\f87bfd7079654c9da4153853c1754c9a\flash\97015e127b864690ba1c8df9efa0f510.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\users\f0650960e1b44cf09d4c72fb0ce987e9\avatar\f9525d6f31e84e07a87d70016ce2e9d8.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\08022851058b4861a04847a60f46171a\flash\d0813028bf304ed9a420652bc68462a0.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\0d64496347db4d8f9f0209eec1e357ea\flash\5806f20bdf5e4f539d227e7b2331bdbb.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\21298266b4b64ea0b1547ed0332b2d7d\flash\2fcd145549b74a42994499e1d9bfa3d8.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\26c3e0772e944d988c66a4cc763684a3\flash\d1dc095a891b48568fc5e6b1fc0a05f8.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\2816651ce2e24a7fb739e3e1a97060ed\flash\56d05d51f2ee485480533a8fbfd19f98.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\293b56458b3a43469bc6e6f6922842da\flash\26723d6eb18240b291285ae771496ff9.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\3a9bed9b5b084b1e911e547b7b5533dd\flash\92aac257dc5b4c31b4d5c839bcc07cd1.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\3c06c7d97da444039bde17f82410071d\flash\5b7df57b5df84589a037f3052f5e59a3.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\3e9b0dbdf7654da9a19dfe782718f67f\flash\903b294f80e542938e581394666159e3.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\3f9dbd72e19c49299076127328b50770\flash\6a0d4e596ea44f5d874b0f6d0cb91461.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\3fd86128b18b42bc80b994671c4095b4\flash\af7c594e5b094a09a99947937801a664.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\4610386875b244f0b20b39d83042c820\flash\15d89599f49d4ade97e47a630682e2fb.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\480617a5e1a2448bbf4daeff0620faf5\flash\13cb560036a04f869b05dbeed44b4f02.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\4b327a2c914245fba763fe5d7ed4d74a\flash\03653854ef1a45eca67aed623f6ac4c8.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\4be91ecb07b14c09bce70ceb7eb66439\flash\aaae5898b35c44baa3abc0e008a99740.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\4be91ecb07b14c09bce70ceb7eb66439\thumbnail\f29b9e8d06914b5eabfa700763a206d6.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\6cae13d0b29b4cecb86697a733c85947\flash\e955385f409b4b6689e9a4ccc9eb4dbd.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\6f0d86c6be1841babfcbdcbe378c47fb\flash\5b953f38798543adaf30999ae1cb23e3.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\75eadaa47f764fd3858fb0caf3bd9390\flash\63a8b54285194f8595c11dbd7e927a31.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\7e0bf791d6e840429564b1f1ed146675\flash\f8b47b19f64e409ab34491aa1c35a278.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\a050ae2d62b348eca2c83cb53edac201\flash\eadb8bdaf96e4ace93f822b9f3d28e2f.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\a9e327dc9bf34b2b97e7bab88b5d6f9b\flash\a5666caa7ba64af38257a425ccccb599.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\c17ad519232d4a66887703b32b3be448\flash\386fec3bcd854444ad8d47f6f4be2937.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\c181d0435f564c629768c375a5657a07\flash\9a593e146ea5422784052432106db77a.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\c2c09e3166034e5f9896dd8fdf70fe7c\flash\45f3efbbca1740b8b84e6975a3c5d125.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\c8eae8843aa549d49213c01e8827bcf4\flash\f69e0a0aae9a44f2a735ddac64a8276e.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\c9f988b97359498fac692d50adff455a\flash\a4e8dfc6fe4e4577a34fafa5871cbe7e.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\ca0d515f1417481c83a4e13cf324526c\flash\632bbad7d297402288a6bb427e4108c3.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\cda2ce0e28a14361be099aec4e4a4729\flash\c3a6e07650ab4fd88b4c6d46fece74dd.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\ce43cf08c09941958bb2d56620768aba\flash\4e4ad71b34ae43988c6d7219ac14b864.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\cf9e9e9db147461c8b0a3d1ca925f8f0\flash\e66e0c73749d4f27b4d5f0715b73cccf.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\d4de10b476bc4202bc52d31844ff29df\flash\ee7bfc44d1614d4c928ae4f60f23b581.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\d732fad02fce4285848e8cff48ab7437\flash\63c62e009fa4458b98f61775d3e0e516.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\de1eeb7ae41c40efbd9ebaf14d556d1f\flash\33c76a0eac4e48ceb2fe729bc3c4fdc3.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\e31a422ed84e4701840756b5defd11d3\flash\32f521d045124001943a2e0b024ac2dc.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\e64d18352b864e51b7edac248e9093a5\flash\e38342946afb45ae991538f291c6bfc4.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\f05e22b6db6b4e8698b1780962fa140e\flash\1fad7c80b7df4b28bddbd74cc1fe89d1.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\users\62eca41487f54017a630b9fee6daee48\avatar\869d196d7b83444d8aa565d12e078cd3.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\users\62eca41487f54017a630b9fee6daee48\banner\7ae60508b05640678f6c94e756918d9b.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\13b305e75b0842d8993d0b6a1f08c875\flash\bbffb736381a41eab80b2c5ef5413d7b.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\13b305e75b0842d8993d0b6a1f08c875\thumbnail\954fb8e8f6ca424f97dbb78d8508b9e8.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\1505287f5ce54269a79cd53a54420dc6\flash\31a597bb40044a91b4cdeb04d7f64085.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\1505287f5ce54269a79cd53a54420dc6\thumbnail\56fb9f0797c747ab999cc2e0bfd6dade.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\1cf9d04ab02d45dd9ebe0742781009c9\flash\28d040cdd4e047ebbe8f670286b8c3bb.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\1cf9d04ab02d45dd9ebe0742781009c9\thumbnail\97adef9495634b7684d1d87a8cf48455.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\2c56d59f27f64e1e95ea6e93bb7ca538\flash\40aaca782ef04ac199e34a1f08c891e1.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\2c56d59f27f64e1e95ea6e93bb7ca538\thumbnail\acc3ba1f6e9b48c694f41e0b77da6835.png" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\7263e10785fe4714a9c340be4218e74c\flash\b380ab1bfdb448b3a28697f0aed65b76.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\7263e10785fe4714a9c340be4218e74c\thumbnail\5acc6e20d4aa4637a0cb3b5d24f71105.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\76801bd4cb9647fa83f1c8c0f784ac76\flash\805168626d3a46959bfdb1df1c3298d5.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\76801bd4cb9647fa83f1c8c0f784ac76\thumbnail\2753e192702f4d4aba6142780c202a6e.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\77e0d6544895480aa134367dbf10b081\flash\05e03ea20c4c43679de1f7a9680b457e.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\77e0d6544895480aa134367dbf10b081\thumbnail\58c0a1d651c94ca7b6c21272d220d827.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\78e8a57f3ffe41e19ff490c9c6742e84\flash\429c4715d9e9473c8d7cfe5cad25adb1.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\78e8a57f3ffe41e19ff490c9c6742e84\thumbnail\742303e45f9747eda084607e37870612.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\7d3665df4e6149b799645cae89945f57\flash\3e9d6d521c9543dea6e7d7eb673e9872.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\7d3665df4e6149b799645cae89945f57\thumbnail\cfc88f07b8d541bb9f3fac94945323be.png" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\85cc887c10df49cb9377472cbb49847b\flash\5b11b3de3a0241fc907e821a9425f5fc.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\85cc887c10df49cb9377472cbb49847b\thumbnail\4c98fc12a72242bb9057da067c3b85d4.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\94759b21feff4cd98645804d63e2c8bf\flash\774193948da84bbbb8cb064a13e0ad38.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\94759b21feff4cd98645804d63e2c8bf\thumbnail\bd2ceef4b61647ddabec9d4feec0bd6d.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\94e2c4f6933a4805849f8fce166c591b\flash\927b1a392ef5423f94570d013267eda7.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\94e2c4f6933a4805849f8fce166c591b\thumbnail\2bc3f2a9edea4d05a4b3b7e5942d9d23.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\b6a384c111564581b88e628356a92b9e\flash\69ae7191b73f4bd88fb9ba341b0563d9.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\b6a384c111564581b88e628356a92b9e\thumbnail\ee93185a1ebb4bcf80fd5eb1fc08128b.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\bde935bbfbec4b2a985e5011f12343c6\flash\1f328809704a4b66b76c255bd8127eca.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\bde935bbfbec4b2a985e5011f12343c6\thumbnail\473fe86af62547f5867c7bcaca85673a.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\bfcdabd60a654c7182e98f599902e60a\flash\77b6bd12d48540588add186ab1f2a3f6.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\bfcdabd60a654c7182e98f599902e60a\thumbnail\2025d24a637843a4a78d6c2e230b3021.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\d772f0764b7d40bca29305fefaef73b6\flash\e9f3d266ca2e4e2abdc09456af775dac.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\d772f0764b7d40bca29305fefaef73b6\thumbnail\55a56a1cda63481999a3f25385764ce8.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\e26577b817f045f1a8e7bdbd0ea4208a\flash\3966370ef79042dc89c438417eabaaa6.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\e26577b817f045f1a8e7bdbd0ea4208a\thumbnail\8e72ba10e8434e20bbe46dde2147ab0a.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\f097f51cc3ff423d940cc1e437f48405\flash\93b00796fef64d33b574ac02b709059b.swf" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\games\f097f51cc3ff423d940cc1e437f48405\thumbnail\bfcc59f24db34552940298d964bdeeb4.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\users\adf0eedaaad94c17ba0cff052570abd1\avatar\bc36ee1b684342349ff43c34fb0daeb3.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\users\adf0eedaaad94c17ba0cff052570abd1\banner\4ce0c90d44cf41a6a9ab868ded240a8a.jpg" />
    <_ContentIncludedByDefault Remove="wwwroot\upload\users\4410865ea98f47d98adfe6855bf22c50\avatar\81abfad1fe274b6e8eaf18856ee4c8cb.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Dto\Player\" />
    <Folder Include="Models\Email\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
